[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/Prospect"
  to   = "/Stats"
  status = 301

[[redirects]]
  from = "/Prospect/*"
  to   = "/Stats/:splat"
  status = 301

[[redirects]]
  from = "/Stat"
  to   = "/Stats"
  status = 301

[[redirects]]
  from = "/Stat/*"
  to   = "/Stats/:splat"
  status = 301
